#Parte 3 - Docker Compose

version: '3'

services:
  statusquo-apache:
    image: abrantedevops/network_services_structure:statusquo-apache
    container_name: statusquo-apache
    ports:
      - 8000:8000
    volumes:
      - ./reports:/dados/www/app02/jornal
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600



