#Parte 3 - Docker Compose

version: '3'

services:
  statusquo-apache:
    image: abrantedevops/network_services_structure:statusquo-apache
    container_name: statusquo-apache
    ports:
      - 8000:8000

  robot:
    image: abrantedevops/network_services_structure:statusquo-robot
    container_name: statusquo-robot
    ports:
      - 8080:8080
    volumes:
      - ./isolated_environment/imagem_for_dockerhub_statusquo/robot/resource.robot:/opt/robotframework/tests:Z
    depends_on:
      - statusquo-apache

