#Parte 3 - Docker Compose

version: '3'

services:
  statusquo-apache:
    image: abrantedevops/network_services_structure:statusquo-apache
    container_name: statusquo-apache
    ports:
      - 8000:8000

  robot-framework:
    image: ppodgorsek/robot-framework:latest
    container_name: robot-framework
    volumes:
      - ./test:/opt/robotframework/tests:Z
    environment:
      - BROWSER=chrome
