#Parte 2 - Ansible-Statusquo

- hosts: all
  become: yes
  tasks:
    - name: Changing the name of Linux
      hostname:
        name: server-statusquo

  #Dockerfile services init
    - name: Installing Docker and Docker Compose
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
        state: present

 # Network Requirement
    - name: Copy network interfaces file
      copy:
        src: ../network/statusquo/interfaces
        dest: /etc/network/interfaces
      notify: Restart network
      tags:
        - network

    - name: Copying the docker-compose.yml file to VM1
      copy:
        src: "../df-compose/statusquo/docker-compose.yml"
        dest: /home/vagrant/

    - name: Running docker-compose
      community.docker.docker_compose:
        project_src: /home/vagrant
        files:
          - docker-compose.yml

    - name: Creating the reports folder
      command: mkdir reports

    - name: Get tstatusquo.py from github
      command: wget https://raw.githubusercontent.com/abrantedevops/Network-Services-Structure/master/test/tstatusquo.py

    - name: Running tstatusquo.py and redirecting to reports folder
      command: sudo python3 /home/vagrant/tstatusquo.py > Log-statusquo.txt && rm tstatusquo.py

    - name: Get resource.robot from github
      command: wget https://raw.githubusercontent.com/abrantedevops/Network-Services-Structure/master/test/resource.robot

    - name: Running resource.robot and redirecting to reports folder
      command: sudo docker run --user root -v /home/vagrant/reports:/opt/robotframework/reports:Z -v /home/vagrant:/opt/robotframework/tests:Z ppodgorsek/robot-framework:latest > Log-virtualhost.txt && sudo cp Log-virtualhost.txt /home/vagrant/reports/ && sudo rm Log-virtualhost.txt && sudo rm resource.robot


# wget do raw do test python statusquo
# executar os arquivos python com redirecionaod > no arquivo .txt 
# criar /reports
# executar o comando do robot framework




  handlers:
    - name: Restart network
      service:
        name: networking
        state: restarted
      tags:
        - network