#Parte 2 - Ansible-Statusquo

- hosts: all
  become: yes
  tasks:
    - name: Alterando o nome do Linux
      hostname:
        name: server-statusquo

  #Dockerfile services init
    - name: Instalando o Docker e o Docker Compose
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
        state: present

 # Network Requirement
    - name: Copy network interfaces file
      copy:
        src: ../network/statusquo/interfaces
        dest: /etc/network/interfaces
      notify: Restart network
      tags:
        - network

 # DNS Requirement
    # - name: Copy dns interfaces file
    #   copy:
    #     src: ../network/dns/resolv.conf
    #     dest: /etc/resolv.conf
  

  
    - name: opt01-ss
      synchronize:
        src: "../isolated_environment/imagem_for_dockerhub_statusquo/"
        dest: "/home/vagrant/"


  handlers:
    - name: Restart network
      service:
        name: networking
        state: restarted
      tags:
        - network