#Parte 2 - Ansible-Statusquo

- hosts: all
  become: yes
  tasks:
    - name: Changing the name of Linux
      hostname:
        name: server-statusquo

  #Dockerfile services init
    - name: Installing Docker and Docker Compose
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
        state: present

 # Network Requirement
    - name: Copy network interfaces file
      copy:
        src: ../network/statusquo/interfaces
        dest: /etc/network/interfaces

    - name: Copying the docker-compose.yml file to VM1
      copy:
        src: "../df-compose/statusquo/docker-compose.yml"
        dest: /home/vagrant/

    - name: Running docker-compose
      shell: |
        sudo docker-compose -f /home/vagrant/docker-compose.yml up -d && sudo rm /home/vagrant/docker-compose.yml
      args:
        executable: /bin/bash

    - name: Restart network
      command: sudo systemctl restart networking
  
    - name: check if reports directory exists
      stat:
        path: /home/vagrant/reports
      register: reports_dir

    - name: create reports directory
      file:
        path: /home/vagrant/reports
        state: directory
      when: not reports_dir.stat.exists

    - name: Get tstatusquo.py from github
      command: wget https://raw.githubusercontent.com/abrantedevops/Network-Services-Structure/dev/test/tstatusquo.py

    - name: Running tstatusquo.py and redirecting to reports folder
      shell: | 
        sudo python3 /home/vagrant/tstatusquo.py > Log-statusquo.txt && rm tstatusquo.py
      args:
        executable: /bin/bash

    - name: Get resource.robot from github
      command: wget https://raw.githubusercontent.com/abrantedevops/Network-Services-Structure/dev/test/resource.robot

    - name: Running resource.robot and redirecting to reports folder
      shell: |
        sudo docker run --user root -v /home/vagrant/reports:/opt/robotframework/reports:Z -v /home/vagrant:/opt/robotframework/tests:Z ppodgorsek/robot-framework:latest > Log-virtualhost.txt && sudo cp Log-virtualhost.txt /home/vagrant/reports/ && sudo rm Log-virtualhost.txt && sudo rm resource.robot
      args: 
        executable: /bin/bash
