#Parte 2 - Ansible-Client

- hosts: all
  become: yes
  vars:
    suporte_public_key_path: /home/suporte/.ssh/id_rsa.pub
    ansible_timeout: 60
  tasks:
    - name: Changing the name of Linux
      hostname:
        name: client

    - name: Installing the Packages
      apt:
        update_cache: yes
        name:
          - acl
          - python3-pip
          - python3-pexpect
          - expect
        state: present

      # Network Requirement
    - name: Copy network interfaces file
      copy:
        src: ../network/client/interfaces
        dest: /etc/network/interfaces
      
    - name: Restart network
      shell: |
        systemctl restart networking
      args:
        executable: /bin/bash
      register: shell_output
      changed_when: false
      no_log: true

      # Create users
    - name: Create users
      become: true
      user:
        name: "{{ item }}"
        shell: /bin/bash
        createhome: yes
        home: "/home/{{ item }}"
        state: present
        password: "{{ '1234' | password_hash('sha512') }}"
      with_items:
        - suporte
        - jornalista

    - name: Generate SSH key pair for suporte
      command: ssh-keygen -t rsa -b 4096 -C "suporte@abranteme.com.br" -f /home/suporte/.ssh/id_rsa -P ""
      become: true
      become_user: suporte

    - name: Generate SSH key pair for jornalista
      command: ssh-keygen -t rsa -b 4096 -C "jornalista@abranteme.com.br" -f /home/jornalista/.ssh/id_rsa -P ""
      become: true
      become_user: jornalista


    - name: Copy SSH key suporte to remote server
      expect:
        command: ssh-copy-id -o StrictHostKeyChecking=no suporte@10.0.128.1
        responses:
          "password": "1234"
      become: true
      become_user: suporte

    - name: Copy SSH key jornalista to remote server
      expect:
        command: ssh-copy-id -o StrictHostKeyChecking=no jornalista@10.0.128.1
        responses:
          "password": "1234"
      become: true
      become_user: jornalista

    - name: Copy temporary sshd_config file to Client
      become: true
      become_user: suporte
      copy:
        src: ../sec_access/veridis/sshd_config
        dest: /tmp/sshd_config

    - name: Copy sshd_config file to remote server
      expect:
        command: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/sshd_config root@10.0.128.1:/etc/ssh/sshd_config
        responses:
          "password": "vagrant"
      become: true
      become_user: suporte

    - name: Restart SSH service on remote server as root
      expect:
        command: ssh -o StrictHostKeyChecking=no root@10.0.128.1 systemctl restart ssh
        responses:
          "password": "vagrant"

    - name: Remove temporary sshd file config
      file:
        path: /tmp/sshd_config
        state: absent