#Parte 2 - Ansible-Statusquo

- hosts: all
  become: yes
  tasks:
    - name: Changing the name of Linux
      hostname:
        name: server-statusquo

  #Dockerfile services init
    - name: Installing Docker and Docker Compose
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
        state: present

 # Network Requirement
    - name: Copy network interfaces file
      copy:
        src: ../network/statusquo/interfaces
        dest: /etc/network/interfaces

    - name: Copy the docker-compose.yml file to VM1
      copy:
        src: "../df-compose/statusquo/docker-compose.yml"
        dest: /home/vagrant/

    - name: Running docker-compose
      become: true
      become_user: root
      shell: |
        docker-compose -f /home/vagrant/docker-compose.yml up -d && rm /home/vagrant/docker-compose.yml
      args:
        executable: /bin/bash

    - name: Restart network
      shell: |
        systemctl restart networking
      args:
        executable: /bin/bash
      register: shell_output
      changed_when: false
      no_log: true
  
    - name: Check if reports directory exists
      stat:
        path: /home/vagrant/reports
      register: reports_dir

    - name: Create reports directory
      file:
        path: /home/vagrant/reports
        state: directory
      when: not reports_dir.stat.exists

    - name: Get tstatusquo.py from github
      get_url:
        url: https://raw.githubusercontent.com/abrantedevops/Network-Services-Structure/dev/test/tstatusquo.py
        dest: /home/vagrant/tstatusquo.py
        mode: 0644

    - name: Running tstatusquo.py
      shell: | 
        python3 /home/vagrant/tstatusquo.py > Log-statusquo.txt && rm tstatusquo.py
      args:
        executable: /bin/bash
      register: shell_output
      changed_when: false
      no_log: true

    - name: Get resource.robot from github
      get_url:
        url: https://raw.githubusercontent.com/abrantedevops/Network-Services-Structure/dev/test/resource.robot
        dest: /home/vagrant/resource.robot
        mode: 0644

    - name: Pull image for robot framework test
      become: true
      become_user: root
      shell: |
        docker pull vanditboy/robot-framework:latest
      args:
        executable: /bin/bash

    - name: Running resource.robot
      become: true
      become_user: root
      shell: |
        docker run --user root -v /home/vagrant/reports:/opt/robotframework/reports:Z -v /home/vagrant:/opt/robotframework/tests:Z vanditboy/robot-framework:latest > Log-virtualhost.txt
      args: 
        executable: /bin/bash

    - name: Redirecting results to reports folder
      become: true
      become_user: root
      shell: |
        cp Log-virtualhost.txt /home/vagrant/reports && rm Log-virtualhost.txt && rm resource.robot
      args:
        executable: /bin/bash
