name: Build/Deploy to Registry Container

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker image for bind-master
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/bind9
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/bind9/dockerfile
                push: false
                tags: abrantedevops/network_services_structure:veridis-bind-master

            - name: Build Docker image for bind-slave
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/bind9/slave
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/bind9/slave/dockerfile
                push: false
                tags: abrantedevops/network_services_structure:veridis-bind-slave

            - name: Build Docker image for nginx-lan
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/lan
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/lan/dockerfile
                push: false
                tags: abrantedevops/network_services_structure:veridis-nginx-lan

            - name: Build Docker image for nginx-wan
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/wan
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/wan/dockerfile
                push: false
                tags: abrantedevops/network_services_structure:veridis-nginx-wan

            - name: Build Docker image for apache
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_statusquo/apache
                dockerfile: ./isolated_environment/imagem_for_dockerhub_statusquo/apache/dockerfile
                push: false
                tags: abrantedevops/network_services_structure:statusquo-apache
        
    scan-images:
        needs: build
        if: ${{ needs.build.result == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Trivy
              run: |
                wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz
                tar zxvf trivy_$(uname -s)_$(uname -m).tar.gz
                sudo mv trivy /usr/local/bin/

            - name: Scan Docker images
              run: |
                trivy image --exit-code 1 --severity HIGH,CRITICAL abrantedevops/network_services_structure:veridis-bind-master
                trivy image --exit-code 1 --severity HIGH,CRITICAL abrantedevops/network_services_structure:veridis-bind-slave
                trivy image --exit-code 1 --severity HIGH,CRITICAL abrantedevops/network_services_structure:veridis-nginx-lan
                trivy image --exit-code 1 --severity HIGH,CRITICAL abrantedevops/network_services_structure:veridis-nginx-wan
                trivy image --exit-code 1 --severity HIGH,CRITICAL abrantedevops/network_services_structure:statusquo-apache

    deploy:
        needs: scan-images
        if: ${{ needs.scan-images.result == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.USER }}
                password: ${{ secrets.PASS }}

            - name: Push image for bind-master
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/bind9
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/bind9/dockerfile
                push: true
                tags: abrantedevops/network_services_structure:veridis-bind-master

            - name: Push image for bind-slave
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/bind9/slave
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/bind9/slave/dockerfile
                push: true
                tags: abrantedevops/network_services_structure:veridis-bind-slave

            - name: Push image for nginx-lan
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/lan
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/lan/dockerfile
                push: true
                tags: abrantedevops/network_services_structure:veridis-nginx-lan

            - name: Push image for nginx-wan
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/wan
                dockerfile: ./isolated_environment/imagem_for_dockerhub_veridis/nginx/wan/dockerfile
                push: true
                tags: abrantedevops/network_services_structure:veridis-nginx-wan

            - name: Push image for apache
              uses: docker/build-push-action@v2
              with:
                context: ./isolated_environment/imagem_for_dockerhub_statusquo/apache
                dockerfile: ./isolated_environment/imagem_for_dockerhub_statusquo/apache/dockerfile
                push: true
                tags: abrantedevops/network_services_structure:statusquo-apache