name: Build/Deploy to Registry Container

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker image for bind-master
              run: docker build -t abrantedevops/network_services_structure:veridis-bind-master ./isolated_environment/imagem_for_dockerhub_veridis/bind9
      
            
            - name: Build Docker image for bind-slave
              run: docker build -t abrantedevops/network_services_structure:veridis-bind-slave ./isolated_environment/imagem_for_dockerhub_veridis/bind9/slave
      
           
            - name: Build Docker image for nginx-lan
              run: docker build -t abrantedevops/network_services_structure:veridis-nginx-lan ./isolated_environment/imagem_for_dockerhub_veridis/nginx/lan
      
       
            - name: Build Docker image for nginx-wan
              run: docker build -t abrantedevops/network_services_structure:veridis-nginx-wan ./isolated_environment/imagem_for_dockerhub_veridis/nginx/wan
      
      
            - name: Build Docker image for apache
              run: docker build -t abrantedevops/network_services_structure:statusquo-apache ./isolated_environment/imagem_for_dockerhub_statusquo/apache
        
    scan-images:
        needs: build
        if: ${{ needs.build.result == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Trivy
              run: |
                wget https://github.com/aquasecurity/trivy/releases/download/v0.42.1/trivy_0.42.1_Linux-64bit.deb
                sudo dpkg -i trivy_0.42.1_Linux-64bit.deb

            - name: Scan Docker images
              run: |
                trivy abrantedevops/network_services_structure:veridis-bind-master
                trivy abrantedevops/network_services_structure:veridis-bind-slave
                trivy abrantedevops/network_services_structure:veridis-nginx-lan
                trivy abrantedevops/network_services_structure:veridis-nginx-wan
                trivy abrantedevops/network_services_structure:statusquo-apache

    deploy:
        needs: scan-images
        if: ${{ needs.scan-images.result == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.USER }}
                password: ${{ secrets.PASS }}

            - name: Push Docker images to DockerHub
              run: |
                docker push abrantedevops/network_services_structure:veridis-bind-master
                docker push abrantedevops/network_services_structure:veridis-bind-slave
                docker push abrantedevops/network_services_structure:veridis-nginx-lan
                docker push abrantedevops/network_services_structure:veridis-nginx-wan
                docker push abrantedevops/network_services_structure:statusquo-apache